### ISSUE TITLE
could you please release the pre-trained model?

### ISSUE THREAD

**Issue by liaozeyi** [P3n9W31/transformer-pytorch#2]
Thanks

**Comment by P3n9W31** [comment]
Sorry about that, I hope this code could help you to understand the operation in the paper. Since I have not tested this code on a public dataset, currently there is no pre-trained model available yet. If you want to use the pre-trained model in your project, I recommend using a model provided by [fairseq](https://github.com/pytorch/fairseq/).

**Comment by liaozeyi** [comment]
ok！ thanks a lot





---Original---
